### ISSUE TITLE
Issue in Xcode when adding swift dependency for fluent-mongo-driver

### ISSUE THREAD

**Issue by bartecheck** [vapor/fluent-mongo-driver#12]
The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/vapor/fluent-mongo-driver/ — 1.0.0-rc.1.2..<2.0.0

<img width="2560" alt="Screen Shot 2020-03-21 at 15 03 24" src="https://user-images.githubusercontent.com/16550752/77228086-22fc3d80-6b85-11ea-8bf3-94b4e58581b6.png">

**Comment by Joannis** [comment]
Hello @bartecheck can you re-upload that image? It seems to have failed during upload.

**Comment by Joannis** [comment]
Did you use the following URL for the dependency?
`https://github.com/vapor/fluent-mongo-driver.git`

**Comment by bartecheck** [comment]
I think I used the link without ".git" ending.
Anyway now is fine.
Thanks!
